#pragma once

enum OBJID { OBJ_PLAYER, OBJ_ITEM, OBJ_MONSTER, OBJ_BULLET, OBJ_SHIELD, OBJ_ROLLBOT, OBJ_BULLETMONSTER, OBJ_ULTIMATE, OBJ_END };

enum ITEMID { ITEM_BULLET, ITEM_GUIDED, ITEM_ULTIMATE, ITEM_SHIELD, ITEM_ROLLBOT, ITEM_END };

enum MONSTERTYPE{ MONSTERTYPE_BOSS, MONSTERTYPE_A, MONSTERTYPE_B, MONSTERTYPE_C, MONSTERTYPE_END};

enum BULLETTYPE { BULLETTYPE_DEFULT, BULLETTYPE_SCREW, BULLETYPE_END };