#pragma once

enum OBJID { OBJ_PLAYER, OBJ_ITEM, OBJ_BULLET, OBJ_MONSTER, OBJ_END };

enum ITEMID { ITEM_BULLET, ITEM_SHIELD, ITEM_END };

enum MONSTERTYPE{ MONSTERTYPE_BOSS, MONSTERTYPE_A, MONSTERTYPE_B, MONSTERTYPE_END};